Subsystem skeletons
FRC4607/Comp-Bot-2024 pull request #1
Opened 2024-01-25 22:52 UTC by Cowpow0987

Added Subsystems and Commands without any logic to be implemented at a later date on other branches.

2024-01-26 02:18 UTC, ItsMajestiX requested changes
This is a good base. However, there are some changes that I would like to see before this is merged, along with the file specific comments I made.

1. Methods that should take values as input in subsystems (setters) should have parameters included.
2. Classes and methods should be documented using [Javadoc](https://www.tutorialspoint.com/java/java_documentation.htm) to describe what they do., what their parameters are, and what (if anything) they return. This is especially useful for making clear the units a function accepts or returns.

2024-01-26 02:18 UTC, ItsMajestiX commented on src/main/java/frc/robot/commands/StartIntake.java
This is probably better off as a RunIntake where the intake stops when the command ends.

2024-01-26 02:18 UTC, ItsMajestiX commented on src/main/java/frc/robot/subsystems/IntakeSubsystem.java
This subsystem needs either a method to limit its power or to set the output of the motor(s) depending on what the purpose of `setIntakePower()` is.

2024-01-27 15:24 UTC, ItsMajestiX requested changes
Very good. This is almost there, just two more things:
1. Make sure to clarify what units the set setpoint functions on the arm and climber expect. I would recommend they be in the same units as the get position/velocity functions.
2. Add a setter and a getter for speed to the intake subsystem.

2024-01-27 17:36 UTC, Cowpow0987 commented on src/main/java/frc/robot/subsystems/IntakeSubsystem.java
SetIntakePower() is setting the max power, so I added one method to set the RPM setpoint and another to get the current RPM

2024-01-27 17:38 UTC, ItsMajestiX approved these changes
Looks good for now. We can go into more detail when we start implementing these.

2024-01-27 17:39 UTC, merged